config/routes.rb
Rails.application.routes.draw do
 
  root "kittens#index"
  
  resources :kittens


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html 
      format.json {render json: @kittens}
    end
  end
  
  def new
    @kitten = Kitten.new
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html 
      format.json {render json: @kittens}
    end
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:notice] = "kitten was updated successfully"
      redirect_to @kitten
    else
      render "edit"
    end 
  end 
  # shows exact same code for updating a form
  # https://stackoverflow.com/questions/42844615/rails-update-method-not-saving-form-data


def destroy
  @kitten = Kitten.find(params[:id])

  @kitten.destroy
  # if @kitten.destroy 
  #   flash[:success] = "kitten was deleted"
  # else
  #   flash[:error] = "failed to delete"
  # end
  
  redirect_to root_path

end



private

def kitten_params
  params.require(:kitten).permit(:name, :age, :cuteness, :softness)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |f| %>
<p>
  <%= f.label :name %> <br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :age %> <br>
  <%= f.text_field :age  %> <br>
</p>

<p>
  <%= f.label :cuteness %> <br>
  <%= f.text_field :cuteness %>
</p>

<p>
  <%= f.label :softness %> <br>
  <%= f.text_field :softness %>
</p>

<p><%= f.submit "save" %> </p>

<% end %>

app/views/kittens/edit.html.erb
<h2>edit your cat</h2>
<%= render "kittens/form" %>

<div><%= button_to "delete", kitten_path(@kitten), method: :delete, data: {confirm: "are you sure you want to delete this event?" }%> </div>

app/views/kittens/index.html.erb
<h2>a list of all cats</h2>


<% @kittens.each do |kitten| %>
<%= link_to kitten.name, kitten_path(kitten)%> <br>
<% end %>

app/views/kittens/new.html.erb
<h2>create a new cat</h2>

<%= render "kittens/form" %>

app/views/kittens/show.html.erb
<h2> <%= @kitten.name %> </h2>

<ul>
  age: <%= @kitten.age %> <br>
  cuteness: <%= @kitten.cuteness %> <br>
  softness: <%= @kitten.softness %> 
</ul>

<div><%= link_to "edit your cat", edit_kitten_path %> </div> <br>

app/views/layouts/_navbar.html.erb
<header>
  <div class="container">
    <ul>
       <div><%= link_to 'home', root_path %></div>
      <div><%= link_to 'create', new_kitten_path %></div>

    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>